### ISSUE TITLE
Carla can't load Noise Repellent plugin

### ISSUE THREAD

**Issue by unfa** [lucianodato/noise-repellent#11]
**Failed to load plugin
/usr/local/lib/lv2/nrepel.lv2/nrepel.so: undefined symbol: fftwf_execute**

![error_131](https://cloud.githubusercontent.com/assets/491704/19246835/9613adf4-8f28-11e6-8599-26d22878c12f.png)

This was compiled from today's git.

**Comment by lucianodato** [comment]
Hello Unfa! Could you tell me what distro are you using? It's probably a compiler flag thing.

**Comment by unfa** [comment]
Hi!
I'm running Linux Mint 18 MATE 64-bit with KX Studio stuff installed on top of that.

**Comment by unfa** [comment]
Btw: I think there is a related issue in Carla project: https://github.com/falkTX/Carla/issues/426

**Comment by mikobuntu** [comment]
Perhaps if @lucianodato could create a port of his plugin without the "Ardour fftw port " then it would work in all applications?. I'm unsure if this is the problem?. If so i can comment out this in the source and rebuild. Anyway I would really find this a useful application to use outside of Ardour. thanks:)

**Comment by lucianodato** [comment]
Ok guys! I'm onto it!

**Comment by lucianodato** [comment]
Should be good now guys! Let me know if it's working for you with the latest master

**Comment by mikobuntu** [comment]
confirmed fixed, great job @lucianodato :)
![noise-repelworking](https://cloud.githubusercontent.com/assets/335217/19649265/15e206fa-99fd-11e6-8c50-bf01bdce5aa5.png)

**Comment by unfa** [comment]
Fantastic! Thank you so much! :)
