### ISSUE TITLE
[Minor issue] Source files and .so have execute permission.

### ISSUE THREAD

**Issue by jrigg** [lucianodato/noise-repellent#12]
All the source files and compiled .so have unnecessary execute permission. It's trivial to change locally, but might be nice to change it in source.

Thanks for your continuing work on this very useful plugin.

**Comment by lucianodato** [comment]
Ok it's done for the installed .so . Not sure how to do it for the compiled one since mkdir -p -m it's broken as I read. I guess I could do it with another line with chmod. Let me know what you think about this.

**Comment by jrigg** [comment]
Quite a few programs install a compiled .so with execute permission. I'm used to using chmod after installing, so if there isn't an easy solution it isn't a big deal. I notice looking through makefiles for other software that some use "install -m 644 ..." for files that don't need to execute.

**Comment by lucianodato** [comment]
Right! That's what I'm doing for the installation. If this is acceptable I will close the report.

**Comment by jrigg** [comment]
Installed file looks good. All the source files still have 755 permissions however.

**Comment by lucianodato** [comment]
I'm intrigued. Why compiled files shouldn't have execution permissions? Is it a security thing? A good practice? I guess I could add a chmod line in makefile but as a begginer linux audio programmer I want to know this. Could you shed some light to me?

**Comment by jrigg** [comment]
It's good security practice to only give execute permission to files that need to execute. I'm so used to doing that after 17 years of Linux use that it looks surprising to me when it isn't done. I was referring to the .c files, README, Makefile etc. in the github source tree - they don't need execute permission.

**Comment by lucianodato** [comment]
Ahh got it!
