### ISSUE TITLE
Using Noise-Repellent for sound design

### ISSUE THREAD

**Issue by unfa** [lucianodato/noise-repellent#17]
Hi!

I find Noise-Repellent a great tool for upping the quality of noisy recordings when I really need to used them. Especially helpful for film work I do.

But also as a sound designer I'm thinking how can I use this tool creatively, to introduce unusual distortion to sound.

I wonder if a creative mode could be added that'd for example allow to make the settings reach far beyond reasonable limits, or introduce some options that could completely mess up the process, resulting in new interesting sounds?

Maybe it's a topic for a special fork of this plugin intended for sound design, rather than noise removal?

**Sound-Proppelant?**

What do you think?

**Comment by lucianodato** [comment]
Hey unfa! 

Noise-repellent is a subtractive spectral processor. You could subtract whatever spectral shape you capture from a waveform. I have used it to do lo-fi de-reverberation on some things for example. A better way to do this kind of creative processing is to draw a spectral shape into a canvas to be subtracted, but that would require some kind of GUI. Noise-repellent code can be modified easily to do any kind of spectral processing. It would imply only changing the subtractive part (it's all commented in the code). The rest of the code is to transform the signal into frequencies and back to waveforms again. So it could be easily forked and modified to make some more musical/sound-designer oriented stuff. 

I'm still learning all this stuff so it's not trivial to me to program a GUI or more fancy LV2 features. For now I prefer to focus on noise-repellent (GUI, saving states. better algorithm, etc) so don't expect me to do that. Maybe in the future, maybe.

By the way, I'm loving you latest tutorials.

**Comment by unfa** [comment]
Thanks, lucianodato!

This sounds promising. I thught about abusing the "learn" funcion by feeding Noise Releppent some stange sound to recognize as noise and then processign a sound where that signal isn't present (like let it learn on a sawtooth wave, and then process vocals) I haven't tried that yet though.

Tutorials? Thanks! I'm really glad to see them being helpful. If you have any ideas for what should I talk about - let me know :)

**Comment by lucianodato** [comment]
Nice work unfa! Like I'd said before a gui for noise repellent seems very far. I'm having troubles understanding some basic lv2 features like atoms so it will take me some time to get there. As for your tutorials you are already doing a great job. Maybe something about recommending plugins for new users could be useful.
