### ISSUE TITLE
Residual Whitening

### ISSUE THREAD

**Issue by lucianodato** [lucianodato/noise-repellent#29]
The approach taken was bad. It's not the residual spectrum that it should be whiten but the reduction applied in each frequency should be modified in such way that the residual noise is close to white so it will made the amount of reduction frequency dependent.

**Comment by FrnchFrgg** [comment]
I commented on your last commit, see there for details.

**Comment by lucianodato** [comment]
What is done in previous versions is not really spectral whitening for reference the algorithm should do what is specified in Röbel paper Efficient spectral envelope estimation and its application to pitch shifting and envelope preservation
