### ISSUE TITLE
Packaging for main distributions

### ISSUE THREAD

**Issue by lucianodato** [lucianodato/noise-repellent#35]
A deb package and an AUR script for starters.

**Comment by lucianodato** [comment]
Are snaps and flatpacks usable for this? I'll have to investigate

**Comment by ohli** [comment]
There ya go:

PKGBUILD for ArchLinux
`
pkgname=noise-repellent
pkgver=0.1.2
pkgrel=1
pkgdesc="An lv2 plugin for broadband noise reduction."
arch=('i686' 'x86_64')
url="https://github.com/lucianodato/noise-repellent"
license=('GPL')
groups=('lv2-plugins')
depends=('fftw' 'lv2')
makedepends=('gcc')
optdepends=('jack: standalone jack client'
            'ardour: intended use')
source=("https://github.com/lucianodato/noise-repellent/archive/$pkgver.tar.gz")
md5sums=('67fd693e80f86a09c2678f13ef1c2958')

build() {
  cd "$pkgname-$pkgver"
  make
}

package() {
  cd "$pkgname-$pkgver"
  make PREFIX=/usr DESTDIR="$pkgdir/" install
}

´

Just tell me if I should publish this to the AUR

**Comment by lucianodato** [comment]
Nice! Thanks Oliver! The only thing that I would change there is that the license is LGPL.

**Comment by ohli** [comment]
You're welcome! Updated the comment.
By the way, thank you for this! Works pretty well 😃

**Comment by lucianodato** [comment]
If it's not much trouble for you I prefer you to upload it since people already knows your audio stuff.

**Comment by ohli** [comment]
Alright, there it is:
https://aur.archlinux.org/packages/noise-repellent

I'll update it for every new release.

You may mention it somewhere in the README, but the Arch users tend to find this out by themselves

**Comment by lucianodato** [comment]
I'm trying to build a snap package for noise repellent. If I'm successful this will be resolved.

**Comment by Pistos** [comment]
Thank you for creating this plugin.  It's the only one I've found that I've been able to get working.

I use Gentoo, and I was able to install without root privileges by:

As root:

    # mkdir /usr/lib64/lv2/nrepel.lv2/
    # chown nonrootuser:nonrootuser /usr/lib64/lv2/nrepel.lv2/

As non-root user:

    % git clone https://github.com/lucianodato/noise-repellent.git
    % cd noise-repellent.git
    % meson build --buildtype release --prefix /usr/lib64/lv2
    % cd build
    % ninja -v
    % ninja install

**Comment by lucianodato** [comment]
thanks! i didn't get your request.

**Comment by ohli** [comment]
Sorry for a little bit OT (regarding gentoo):

The little AUR-script from above made it to the Arch-Community repo, so please change the link in the README to https://www.archlinux.org/packages/community/x86_64/noise-repellent/

Thanks

**Comment by lucianodato** [comment]
ok. done!

**Comment by trebmuh** [comment]
Hi @lucianodato , just to let you know that I made a package for the (coming soon) LibraZiK-3 from Git master 9efdd0b. This package should work on any Debian Buster, and maybe a bunch of .deb based distro.

**Comment by lucianodato** [comment]
Thank you sir! I do provide binaries now so no real need for packages.
