### ISSUE TITLE
New separate plugin for adaptive noise reduction focused on speech

### ISSUE THREAD

**Issue by lucianodato** [lucianodato/noise-repellent#41]
This might be a good idea since more parameters could be exposed like threshold bands and smoothing tweaking. Need feedback on this.

**Comment by lucianodato** [comment]
There are some ways to do this other separate plugin zero latency. That could be really useful.

**Comment by lucianodato** [comment]
Using new Xiph's RNNoise library could be the best solution

**Comment by lucianodato** [comment]
Already working on this

**Comment by trebmuh** [comment]
👍

**Comment by lucianodato** [comment]
Related to issue #8

**Comment by lucianodato** [comment]
The first rough version is done at https://github.com/lucianodato/speech-denoiser. Now I might integrate it to noise repellent as a VAD
