### ISSUE TITLE
Sidechain input for noise source?

### ISSUE THREAD

**Issue by unfa** [lucianodato/noise-repellent#52]
Would it be possible to introduce a secondary sidechain input for noise print capture?

Possible use cases are:

Using two microphones in a noisy environment to capture a signal (voice) + noise on one mic, and just the background noise on the other mic and use the information to get a clean signal (with no background noise).

I know modern smartphones do just that for improved call sound quality with a secondary microphone.

The problem is - simple mixing with polarity flip won't work, because of phase, EQ and delay differences.

However - is a secondary input could be used as live noise source for spectral analysis and noise removal - I suspect  the effects could be very good.

**Comment by lucianodato** [comment]
That is called active noise cancellation. This algorithm is not that unfortunately. Capturing the noise profile and reducing it are two separate process that cannot run at the same time.
