### ISSUE TITLE
RNNoise - neural network to improve noise cancelling

### ISSUE THREAD

**Issue by unfa** [lucianodato/noise-repellent#53]
I have stumbled upon this project on Xiph.org and I thought it could be a great resource fro Noise Repellent.
They have created a fast, realtime and cpu-efficient noise suppression tool using a neural network.

Source code and whitepaper are available:

https://people.xiph.org/~jm/demo/rnnoise/

**Comment by lucianodato** [comment]
Hey unfa! I have a plugin based on that library. It's called speech-denoise but the problem is that this library only supports 16 bit raw data and is quite difficult to change that for what I can tell. But definitely possible.

**Comment by lucianodato** [comment]
This could be used as a VAD for the adaptive mode

**Comment by unfa** [comment]
Awesome! I thought Vocal Denoiser is just a pre-tuned simpler version of Noise Repellent.
I need to make a video about these two :)
