### ISSUE TITLE
Apply a preset and the associated state.ttl to a set of files

### ISSUE THREAD

**Issue by s-leroux** [lucianodato/noise-repellent#56]
Hi Luciano, and first of all congratulations for the great work on noise-repellent.

I started using that plug-in from Ardour. But I wonder if it is possible to apply noise-repellent in batch to a set of files, given the `state.ttl` file and the preset found in an Ardour XML file:

```
        <lv2 last-preset-uri="" last-preset-label="" parameter-changed-since-last-preset="1" state-dir="state2">
          <Port symbol="reduction" value="10"/>
          <Port symbol="offset" value="0"/>
          <Port symbol="release" value="150"/>
          <Port symbol="masking" value="5"/>
          <Port symbol="transient_protection" value="1"/>
          <Port symbol="whitening" value="0"/>
          <Port symbol="noise_learn" value="0"/>
          <Port symbol="adaptive_noise_learn" value="0"/>
          <Port symbol="reset_noise_profile" value="0"/>
          <Port symbol="Residual_listen" value="0"/>
          <Port symbol="enable" value="1"/>
        </lv2>
```

I suspect it might be possible with [jalv](https://drobilla.net/software/jalv), [lv2apply](http://drobilla.net/man/lv2apply.1.html) or a similar LV2 container usable from the command line, but I can't find how to do it. Any idea or suggestions?

**Comment by FrnchFrgg** [comment]
The .ttl file does *not* contain the noise profile, it is saved elsewhere (with the LV2 state extension). So your approach is doomed to begin with.

**Comment by s-leroux** [comment]
Interesting @FrnchFrgg .

Attached is the `state.ttl` (with the .txt extension added for GitHub to upload it).
That file that looked to me as the noise profile.
[state.ttl.txt](https://github.com/lucianodato/noise-repellent/files/1958587/state.ttl.txt)

_"it is saved elsewhere (with the LV2 state extension)."_
Could you precise the location?

_"What you can do, however, is use NR in adaptative mode, since it would create its profile on the fly. Not as good a result, but still usable."_
It is not an option. I switched from Audacity noise reduction plug-in because it was not satisfactory and Audacity WAV output in batch chains was downsampled to 16 bits, so if I change my workflow, this sill be for a higher output quality. Not a lower one.

_"So your approach is doomed to begin with."_
I can't believe there is no way to restore the state saved by the plug-in. I suspect this is related to the code [here](https://github.com/lucianodato/noise-repellent/blob/master/src/nrepel.c#L222), but I can't see how the plug-in locate the "right" profile file.

**Comment by FrnchFrgg** [comment]
When you use the preset normally with ardour, the noise profile is in
<session path>/plugins/<number1>/state<number2>/
where <number1> represents the plugin id in the session, and <number2> increases at each saved modification.

When you save a *preset* (with the top buttons in the plugin UI), they end up as
~/.lv2/<plugin-name>_<preset-name>.lv2/<preset-name>.ttl

An example of which is following
`@prefix atom: <http://lv2plug.in/ns/ext/atom#> .
@prefix lv2: <http://lv2plug.in/ns/lv2core#> .
@prefix pset: <http://lv2plug.in/ns/ext/presets#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix state: <http://lv2plug.in/ns/ext/state#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<>
	a pset:Preset ;
	lv2:appliesTo <https://github.com/lucianodato/noise-repellent> ;
	rdfs:label "test" ;
	lv2:port [
		lv2:symbol "Residual_listen" ;
		pset:value 0.0
	] , [
		lv2:symbol "adaptive_noise_learn" ;
		pset:value 0.0
	] , [
		lv2:symbol "enable" ;
		pset:value 1.0
	] , [
		lv2:symbol "masking" ;
		pset:value 5.0
	] , [
		lv2:symbol "noise_learn" ;
		pset:value 0.0
	] , [
		lv2:symbol "offset" ;
		pset:value 3.0
	] , [
		lv2:symbol "reduction" ;
		pset:value 10.0
	] , [
		lv2:symbol "release" ;
		pset:value 150.0
	] , [
		lv2:symbol "reset_noise_profile" ;
		pset:value 0.0
	] , [
		lv2:symbol "transient_protection" ;
		pset:value 1.0
	] , [
		lv2:symbol "whitening" ;
		pset:value 0.0
	] ;
	state:state [
		<https://github.com/lucianodato/noise-repellent#fftsize> "1024"^^xsd:int ;
		<https://github.com/lucianodato/noise-repellent#nwindow> "643.0"^^xsd:float ;
		<https://github.com/lucianodato/noise-repellent#FFTp2> [
			a atom:Vector ;
			atom:childType atom:Float ;
			rdf:value (
				"0.03420767"^^xsd:float
				"0.06960466"^^xsd:float
				"0.0789343"^^xsd:float
                                [...snip...]
				"0.00000218"^^xsd:float
				"0.00000229"^^xsd:float
				"0.00000282"^^xsd:float
			)
		]
	] .`

**Comment by lucianodato** [comment]
Could this be considered fixed with Robin's work on lv2file?
