### ISSUE TITLE
ninja installs to /usr/local/nrepel.lv2

### ISSUE THREAD

**Issue by borgdylan** [lucianodato/noise-repellent#57]
When updating the plugin, I noticed the switch to meson. After runnign meson and ninja to build, I noticed that ninja was not installing like make used to i.e. to /usr/local/lib/lv2/nrepel.lv2. I think teh new install locatin is outside the lv2 probing location.

**Comment by lucianodato** [comment]
You'll have to pass a prefix as explained in README.

**Comment by borgdylan** [comment]
Thanks. It would be nice to have a makefile that wraps meson and ninja.

**Comment by lucianodato** [comment]
Maybe a bash script. I used to have one but somehow I removed it. I could re-add it if you like.

**Comment by borgdylan** [comment]
That would be nice. The meson/ninja combiantion is new to peole not working on GNOME, and a script for building would help out. Most people are used to make/auto-tools which usually get configured with the right prefixes from the start.

**Comment by lucianodato** [comment]
As far as I know meson is not gnome specific and lots of projects outside of gnome are migrating to it. Generally is way less headache prone to developers. In the case of this simple plugin it's not that different to autotools that's true. Anyways I will upload the install script during the week. Thanks for the suggestion.

**Comment by lucianodato** [comment]
I upload a build script and updated the readme. It automatically recognizes if you are on linux or macos. Feel free to close this if this satisfies you.

**Comment by borgdylan** [comment]
The script works as expected! Thank you.
