### ISSUE TITLE
Undefined symbol: fftwf_plan_r2r_1d

### ISSUE THREAD

**Issue by jrigg** [lucianodato/noise-repellent#6]
Just tried latest git code on Debian 8 amd64, hosted in jalv.gtk. Plugin failed to instantiate, with error message:
``undefined symbol: fftwf_plan_r2r_1d``

Version from a few days ago works fine.

**Comment by lucianodato** [comment]
Should be good now. Sorry for the inconvenience. I will work on DEV branch now to not break master. Let me know if it's fixed in your machine.

**Comment by jrigg** [comment]
It works now. Thanks for fixing (and thanks for making this plugin available).

**Comment by lucianodato** [comment]
Great! I will close it then. It's the least I could do for such a great community!
