### ISSUE TITLE
How to execute the project?

### ISSUE THREAD

**Issue by bouderb** [lucianodato/noise-repellent#62]
After the installation, what should I do to have the interface ? What I have to execute ?

Thanks for your work !

**Comment by trebmuh** [comment]
You need a LV2 host since noise-repellent is a LV2 plugin.
What operating system are you running? Which distribution (in case of linux)?

**Comment by bouderb** [comment]
thanks for your response .
ok ! 
I'm on Ubuntu 16.04. have you a LV2 host that you could advice to me ?

**Comment by MuruganR96** [comment]
`LV2, an acronym for Linux Audio Developer's Simple Plugin API (LADSPA) version 2, is an open standard for audio plug-ins and matching host applications. It includes support for audio synthesis (generation) and digital signal processing of digital audio and MIDI.`

@trebmuh  please explain us. how to use this **noise-repellent** project in LV2 host. :)

**Comment by trebmuh** [comment]
@bouderb you can use Ardour.

**Comment by bouderb** [comment]
@trebmuh Do you how to install it in Ardour ? 
thanks

**Comment by trebmuh** [comment]
Just put it in you LV2_PATH and ardour will find it, such as ~/.lv2/ .

**Comment by bouderb** [comment]
Ardour don't find lv2 noise repellent plugin.. That is the the path where the folder is : /usr/lib/lv2/nrepel.lv2 
Do you have an idea about my issue ? 
Thanks a lot

**Comment by trebmuh** [comment]
Because I'm on a French locale, I can find noise repellent by searching "répulseur de bruit" in the Ardour plugin manager. The plugin can also be find with: New Plugin -> By Creator -> Luciano Dato
