### ISSUE TITLE
How to install on Raspberry Pi Model 3B running Ubuntu Mate 16.04?

### ISSUE THREAD

**Issue by yatharth-hub** [lucianodato/noise-repellent#66]
Being very new to Linux, I am trying to install noise-repellent on a Raspberry Pi running Ubuntu Mate 16.04, but no luck. Then I came across a command line on the internet which says install using Snaps.

Tried that as well but got this error - "noise-repellent" is not available on edge for this architecture (armhf) but exists on other architectures (amd64, i386).

Any guidance shall really be helpful.

Thanks.

**Comment by lucianodato** [comment]
This should be fixed with https://github.com/lucianodato/noise-repellent/releases/tag/v0.1.5. Now I provide binaries that should run on the raspberry pi
