### ISSUE TITLE
Changing tag system

### ISSUE THREAD

**Issue by dvzrv** [lucianodato/noise-repellent#69]
Hi! I'm currently packaging noise-repellent for Arch Linux.
For consistency it would be awesome, if the tagging system (with `v` or without `v`) would remain consistent over releases.

Changing the tag system (back and forth) leads to a lot of ignored tags in the new version detection system, as the versions with `v` order before the ones without `v`.

**Comment by lucianodato** [comment]
Ok good point. Didn't know that. I'll revert it. Thanks!

**Comment by lucianodato** [comment]
Ok should be good now. Let me know if you find any other quirk
