### ISSUE TITLE
Crashing in ardour

### ISSUE THREAD

**Issue by spectromas** [lucianodato/noise-repellent#7]
Hi, you tried to contact me on irc but I was away and you were offline when I came back. 
This is the bug report I filed about the issue, rgareus mentioned that it appeared to be caused/re;ated to noise-repellent, although he did also seem to think that something is ardour wasn't right from the gdb output - http://tracker.ardour.org/view.php?id=6988.

I just tried the latest master from here but there still seems to be a crash. rgareus did mention that it can be worked around by not having the play head at zero if that helps reproduce it, he said he was at least able to get the errors from the project attached to the bug report. I know of at least one other person who was getting the error and a crash so it could be a regression in ardour. 

Anyway, really just posting this as a way to communicate about it, may not be related to noise-repellent. Feel free to hit me up on irc if you see me there.

**Comment by lucianodato** [comment]
I couldn't make it crash here. I'm using ardour 5.1 from falktx repo. Did you compile it yourself?

**Comment by lucianodato** [comment]
Another work around could be using the bounce+replace action to render the region without noise and then removing the plugin. Last time I tried that works well and it also removed the latency introduced by the plugin.

**Comment by spectromas** [comment]
I'm using the binaries directly from ardour.org, 5.3 right now. 
I've been doing the bouncing and it does work well. I actually had a crash without your plugin loaded or enabled so I think it is something in ardour that's causing it.
