### ISSUE TITLE
Program sord_validate found: NO

### ISSUE THREAD

**Issue by cudanexus** [lucianodato/noise-repellent#70]
when I ran `meson build --buildtype release --prefix /media/mustafa/ubuntu_backup/Projects/aa/noise-repellent/build`
Even Install `sudo apt install sordi`
```
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: nrepel.lv2
Native c compiler: cc (gcc 5.4.0-6ubuntu1)
Program sord_validate found: NO
Program cp found: YES (/bin/cp)
```

**Comment by lucianodato** [comment]
First of all sorry for the extremmely long delay (life gets in the middle). Hmmm yeah I need to replicate this in my local machine. Unfortunately this will take me quite a lot of time since I'm on a windows machine now. Are you still having this issue?

**Comment by lucianodato** [comment]
You don't need sordi in order for the plugin to work is just there for development purposes. Closing now!
