### ISSUE TITLE
plugin version is no longer set

### ISSUE THREAD

**Issue by x42** [lucianodato/noise-repellent#71]
The following two are mandatory

* http://lv2plug.in/ns/lv2core#minorVersion
* http://lv2plug.in/ns/lv2core#microVersion

They used to be set in older versions (prior to meson builds), which leads to a problem: liblilv prefers plugins with later version number. -- Currently older nrepel builds with a lv2:minorVersion are preferred over newer ones without.

**Comment by x42** [comment]
Parent issue: https://discourse.ardour.org/t/noise-repellent-profiles-lost-when-moving-project-to-another-machine/104769/5

**Comment by lucianodato** [comment]
Thanks for reporting Robin. I'll take a look next week

**Comment by lucianodato** [comment]
Ugghhh my bad! I didn't looked at it back then! I'll do it this time!
