### ISSUE TITLE
Unable to install .dll in Windows 10

### ISSUE THREAD

**Issue by racalle** [lucianodato/noise-repellent#72]
Hello,

I am interested in using your dll under windows. I was unable to load them into Audacity or "Wavosaur" sound editors, impossible in 64/32 bit dll formats. I'm using Windows 10 64 bit at the moment. 

I have asked another person try to install in Ardour / mixbus under windows and impossible for them too.

¿Is there any special requeriment in order to install? ¿Did someone successfully installed noise-repellent under a DAW in Windows? 

Gracias!

**Comment by lucianodato** [comment]
Hi! I don't remember if these dlls where statically compiled. I'll try to take a look and get back to you

**Comment by Screeen** [comment]
Hi, I can't load the plugin using Ableton Live 9 or n-Track on Windows 10, either.

**Comment by TheEnbyperor** [comment]
It appears the DLL requires Cygwin DLLs, so I'd recommend installing Cygwyn and seeing if that fixes anything.

**Comment by JMStep** [comment]
Tried installing Cygwin and still no change. Doesn't want to work with Ardour 6.1 on Windows 10 64 bit. No detail is given in the Ardour log, just that it "Failed to instantiate plugin."

**Comment by asdkant** [comment]
I've tried to use the x86_64 windows version of the [0.1.5 release](https://github.com/lucianodato/noise-repellent/releases/tag/0.1.5) under win10 with audacity. I placed the whole folder under 
```
C:\Users\{username}\AppData\Roaming\LV2\
```

Audacity recognizes the plugin but when I try to use it I get an error saying:
![image](https://user-images.githubusercontent.com/3915542/100629790-7758df00-3308-11eb-86e6-ffa0129784b3.png)

it looks like it may be related to this issue.

**Comment by geoflipman** [comment]
Hi. I'm also seeing this problem in Ardour 6.9 on Windows 10 64 bit.  I got two error messages:

"2021-09-15T14:57:17 [ERROR]: LV2: Failed to instantiate plugin https://github.com/lucianodato/noise-repellent"

"Ignoring invalid LV2 plugin (missing name, no ports)"

I tried to look through the .ttl files, and compared them to the standard a-eq plugin .ttls, and although there are differences, there is nothing that looks like missing ports.

**Comment by lucianodato** [comment]
Hi all! Sorry for the delay. I'll try to look into it and make a fix release. There are several problems related to this.

**Comment by lucianodato** [comment]
This is likely to be caused because it is being compiled using cygwin which is not very smart on my behalf. I need to build a visual studio project for it. It will take some time.

**Comment by lucianodato** [comment]
@racalle Hi! I've manage to create good dlls for next version. If you want you can test them downloading a build from here [https://github.com/lucianodato/noise-repellent/suites/6113112035/artifacts/212486087](url) for a 64 bit build or here for 32 bit one [https://github.com/lucianodato/noise-repellent/suites/6113112035/artifacts/212486085](url). Let me know if you find any issue

**Comment by lucianodato** [comment]
I've done the testing and with the newly released version v0.2.0 this should work. I'm going to close it. Any troubles encountered let me know.
