### ISSUE TITLE
Noise repellent makes lv2 hosts crash on Windows 10

### ISSUE THREAD

**Issue by Anvolne** [lucianodato/noise-repellent#73]
Windows 10 Version 2004 Build 19041.630

Cygwin packages installed (dependency of nrepel): fftw3
C:\cygwin64\bin in System PATH variable

Noise repellent makes [Carla](https://github.com/falkTX/Carla) unresponsive and have to be killed using task manager.
It also crashes Audacity with a "Couldn't instantiate effect" message.

I have no idea how to get logs from Carla on Windows, but if it helps at all, I got an audacity crash report with an access violation.
[Audacity_dbgrpt-10532-20201126T171038.zip](https://github.com/lucianodato/noise-repellent/files/5604044/Audacity_dbgrpt-10532-20201126T171038.zip)

**Comment by lucianodato** [comment]
Oh man! I'm sorry! I'll look into it!

**Comment by lucianodato** [comment]
This is likely to be caused because it is being compiled using cygwin which is not very smart on my behalf. I need to build a visual studio project for it. It will take some time.

**Comment by lucianodato** [comment]
Remove due to duplication
