### ISSUE TITLE
LinuxAudio.Plugin flatpak

### ISSUE THREAD

**Issue by herzenschein** [lucianodato/noise-repellent#75]
Hello,
could this lv2 plugin be packaged as a flatpak?
It would be particularly convenient for using apps like Ardour and similar audio tools from flathub, as this plugin isn't available on all distros.

**Comment by lucianodato** [comment]
I've tried many time to do that. Also snaps. Thing is that this is a plugin so it cannot run isolated from the OS, it needs to be visible by the host. I admit it I did this few years back and that wasn't possible. It might be now. I'll try to look at it.
