### ISSUE TITLE
Add to README.md that: Noise Repellent is also in the Kx Studio repositories

### ISSUE THREAD

**Issue by fernando-inf** [lucianodato/noise-repellent#82]
Hi.

Add to README.md (# Install) that: Noise Repellent is also in the Kx Studio repositories:

Plugins: https://kx.studio/Repositories:Plugins
Add Kx Studio repositories (.deb): https://kx.studio/Repositories

**Comment by lucianodato** [comment]
Hey! Thanks Fernando! I'll include it in the next release
