### ISSUE TITLE
Request: A flatpak version of this plugin

### ISSUE THREAD

**Issue by srahman53171618** [lucianodato/noise-repellent#87]
Issue: Cannot use this (awesome) plugin with flatpak versoins of DAWs. A lot of audio plugins are no available as flatpaks (LSP, TAP, x42) and when I install the flatpak version of those plugins, they work with flatpak versions of DAWs. I tried various versions of copying over the files into folders which flatpaks seem to access for other plugins, but DAW still doesn't pick up the plugin. I do not know how much work this would involve but if it is not too much work, a flatpak version of this plugin would be much appreciated.

**Comment by pms967** [comment]
You're asking for the impossible. Flatpak and the likes are meant to distribute self-contained applications which runs "isolated" from one another and the host system. AFAIK there's no way for an app distributed that way to use libraries (and plugins, etc) which are not included in the app package itself. 

Bottom line: do NOT use flatpak (or the likes) to install a DAW (or any other software which may require 3rd party libraries/plugins not included in the distribution package). It's pure nonsense.

A DAW must be installed via native packages (like deb, rpm, etc... whatever is used by your distro), or manually (via tar, zip, or whatever) on the native host system.

**Comment by srahman53171618** [comment]
I understand your point but I am currently using the flatpaks version of Ardour as well as LSP plugins, x42 plugins, tap plugins, calf plugins all installed as flat packs

**Comment by lucianodato** [comment]
@srahman53171618 that's awesome! can you link something here with more details about it? I tried to create a snap package in the past and hit the wall like pms067 explained

**Comment by srahman53171618** [comment]
@lucianodato apologies for the late reply and for not including more information in my initial post. Here is what I have been able to find. 

This base extension seems to have been started in 2020 to provide the base for audio plugins in flatpak form:
https://github.com/flathub/flathub/pull/1460
https://github.com/flathub/org.freedesktop.LinuxAudio.BaseExtension

I don't know which is the correct version (just a noob here when it comes to using github) but they're both by the same user and seem to be about the same thing. There is also more discussion here:
https://discourse.flathub.org/t/proposal-for-audio-plugins/399

Lastly this seems to be the github repo for the LSP flatpak plugin:
https://github.com/flathub/org.freedesktop.LinuxAudio.Plugins.LSP

Others can be found using the command `flatpak search plugins` via the the terminal. I am linking since I figure that will be open source for sure and since I know the plugins work with flatpak Ardour. 

Thank you

**Comment by gspe** [comment]
Hi, I just want to say that this plugin works correctly with the Flatpak version of Ardour.
Just move the plugin to ~/.lv2 dir and restart Ardour before using the plugin.

**Comment by lucianodato** [comment]
Thanks for your input. Solves the meantime

**Comment by srahman53171618** [comment]
@gspe I can't believe the solution was that easy. I literally placed the file everywhere other than ~/.lv2 . @lucianodato this does solve the issue for now although it is a bit of a workaround. Please let me know if you want me to close the issue. Thanks once again everyone.

**Comment by lucianodato** [comment]
To me that's good enough. For now I would prefer third parties to provide packages.

**Comment by lucianodato** [comment]
I think he referred in terms of the project providing a flatpak. Still I prefer for third parties to provide it.
