### ISSUE TITLE
0.2.0 requires a meson wrap, but that can not be used for system's packaging

### ISSUE THREAD

**Issue by dvzrv** [lucianodato/noise-repellent#92]
Hi! When trying to upgrade the package for Arch Linux I ran into the issue, that the libspecbleach library is now required and only exposed as a wrap in this project.

This is problematic for system's packaging, as we would not link this statically, unless you provide the sources for this directly.
Using meson wraps downloads the internet during configure/compile time and this is against distribution policies. The library is provided separately and can be used by other targets, which is why (from a distribution perspective) it makes no sense to package several instances of it in different projects.

It would be great if this could be made a user choice via meson_options.txt. As is, I am not able to upgrade the package.

**Comment by lucianodato** [comment]
Thanks! I'll look into this

**Comment by lucianodato** [comment]
@dvzrv  From what I'm looking at in meson documentation doing something like 
`
libspecbleach_dep = dependency('libspecbleach', fallback : ['libspecbleach', 'libspecbleach_dep'], default_options: ['default_library=static'], required: true)
`
would do it. Is there something specific that I might not know that you need? This way I think the meson_options file is not needed. Let me know what you think.

**Comment by lucianodato** [comment]
Should be fixed in v0.2.1 . Let me know otherwise!
